# Generated by Django 3.1.2 on 2020-10-21 04:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_take', models.IntegerField(default=0)),
                ('deal_money', models.IntegerField(default=0)),
                ('user_give', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='account.profile')),
            ],
            options={
                'db_table': 'Deal',
            },
        ),
    ]
