# Generated by Django 3.1.2 on 2020-10-20 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yammiDeal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deal',
            name='user_take',
            field=models.IntegerField(max_length=500),
        ),
    ]
